### ISSUE TITLE
Corregir pom.xml

### ISSUE THREAD

**Issue by adrmorver** [DP1819AVMA/D01-Introduction#1]
**-** Problema:
El `<artifactId>Acme-shout</artifactId>` del pom.xl no corresponde con el de la diapositiva vista en clase.

**-** Solución:
Cambiar el `<artifacId>Acme-shout</artifactId>` a `<artifactId>Acme-Shout</artifactId>`

**Comment by vicrosa25** [comment]
Eso no cambia, la url del proyecto. Es necesario cambiar el archivo web.xml. Lo cambio
